### ISSUE TITLE
Create a Title Screen

### ISSUE THREAD

**Issue by KonechyJ** [KonechyJ/PyGameDoodle_JumpClone#4]
As it stands the game just starts when played, so it might be fun to have the game play loop start after a Title Screen is shown. The only requirement I really have would be to have the screen have a PLAY! button to start the game. Any other features are yours to create. Just of the top of my head a controls or about button might be fun.

**Comment by oneamanish** [comment]
see my pull req.

**Comment by rclamb27** [comment]
Created a pull request for a title that is interactive.
